### DISCUSSION TITLE
Static Builds for Netlify etc

### DISCUSSION THREAD

**Discussion by edjw** [benbjurstrom/prezet#128] [Show and tell]
I've been experimenting with making a static build with "spatie/laravel-export" so that a Prezet site could go on a service like Netlify.

I haven't tried to make search work. It might be possible to use a tool like [Pagefind](https://pagefind.app/docs/running-pagefind) either in the `after` hook of laravel-export or in the Github action, along with some clientside JS to get that working.

I think this below is working now though for static builds of a Prezet site.

1. Run `composer require spatie/laravel-export`

2. Use a Github Action like this below. Set `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID` as secrets and `DEPLOY_URL` as a variable in your Github Action.

It's a bit hacky. The issue is that laravel-export seems to need APP_URL to be set to localhost for its server to work. But then you want hrefs etc to be set to your Netlify production URL in the html files that laravel-export generates.

```yaml
name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.DEPLOY_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: dom, curl, libxml, mbstring, zip

      - name: Install PHP Dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Node Dependencies
        run: npm ci

      - name: Build Assets
        run: npm run build

      - name: Create env
        run: |
          cp .env.example .env
          php artisan key:generate
          sed -i "s|APP_URL=.*|APP_URL=http://localhost|" .env
          sed -i "s|ASSET_URL=.*|ASSET_URL=http://localhost|" .env
          touch database/database.sqlite
          php artisan migrate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Export Pages
        run: php artisan export --skip-before --skip-after

      - name: Update URLs
        run: |
          find dist -type f -name "*.html" -exec sed -i "s|http://localhost|${{ vars.DEPLOY_URL }}|g" {} +
          find dist -type f -name "*.css" -exec sed -i "s|http://localhost|${{ vars.DEPLOY_URL }}|g" {} +
          find dist -type f -name "*.js" -exec sed -i "s|http://localhost|${{ vars.DEPLOY_URL }}|g" {} +
          find dist -type f -name "*.xml" -exec sed -i "s|http://localhost|${{ vars.DEPLOY_URL }}|g" {} +

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy --dir=dist --prod --message "${GITHUB_SHA::8}"

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: laravel-logs
          path: storage/logs/laravel.log

```
